### ISSUE TITLE
Decide when to hide sidebar nav

### ISSUE THREAD

**Issue by mojavelinux** [webtide/jetty.website#3]
In the Antora default UI, the sidebar nav on the left serves two purposes:

* Present the hierarchy of pages in the current component version (or versionless component)
* Provide a collapsible drawer that lists all the component versions in the site (hidden by default)

It's customary to hide this sidebar nav, or just the hierarchy of pages, for certain component versions. One such example is the versionless ROOT component, or home component. Since the organization of landing pages in the home component tend to be flat and reachable by other means (such as the topbar nav), the sidebar nav just becomes redundant. We can decide to hide the sidebar nav on these pages. See the [Asciidoctor docs](https://docs.asciidoctor.org) for an example of how that might look.

Do you want the sidebar nav to be hidden on the landing pages (i.e., pages in the ROOT component) to allow the main content of those pages to stretch to the left margin?

**Comment by jmcc0nn3ll** [comment]
IMO

Hide on the ROOT component.

Which is better?  

- jetty.org/documentation
- docs.jetty.org

I am leaning toward the second one since it looks cleaner.  Regardless, the documentation landing page should show the component sidebar.

This may mean we have javadoc.jetty.org with a landing page of javadoc links.

Regarding the documentation itself, when in a component for a given version (operations 12) the sidebar ought to look like this:

Contribution Guide (link to)
Developer Guide (link to the same version, so 12)
____________
TOC (Operations 12)


We haven't discussed it, but we may want to deep link, or chop out certain high-profile items out of the monolithic documentation and make their own guides.  A shortcut to a common destination, but that could just as easily be managed with a proper landing page for the Operations Guide, or the Developer Guide. I could easily see it looking like this.

Contribution Guide (link to)
Developer Guide (link to the same version, so 12)
Jetty Client (deep Link)
Jetty Maven Plugin (deep link)
____________
TOC (Operations 12)

Something we'll need to discuss.

@sbordet, with all of the documentation coming together....does the separation of Operations and Developer make sense? We we were to consolidate, now would be the time.

@mojavelinux looking for guidance on the best way something like this ought to be presented.

**Comment by mojavelinux** [comment]
> Hide on the ROOT component.

Let's give that a try and see how it works out.
